name: "Build customized NixOS LiveCD ISO"
on:
  push:
  schedule:
    - cron: '30 1 * * */3'
jobs:
  buildiso:
    if: (startsWith(github.event.head_commit.message, 'buildiso:') || (github.event_name == 'schedule'))
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H')"
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
    - name: Install nixFlake
      uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
    - name: Configure Nix to enable flake
      run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
    - name: Update flake.lock, show drv, and calculate the hashes
      id: update
      run: |
        nix flake update --recreate-lock-file
        nix show-derivation ".#niximg" > niximg.drv
        cat ./flake.lock
        cat ./niximg.drv
        echo "::set-output name=flake::$(sha512sum ./flake.lock|cut -d " " -f 1)"
        echo "::set-output name=niximg-drv::$(sha512sum ./niximg.drv|cut -d " " -f 1)"
    - name: Send starting message to the telegram channel
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          The `${{ github.workflow }}` workflow at `${{ steps.date.outputs.date }}` has started.
          - triggered by `${{ github.event_name }}`
          - `flake.lock` SHA-512: `${{ steps.update.outputs.flake }}`
          - derivation SHA-512: `${{ steps.update.outputs.niximg-drv }}`
          #niximg #started
    - name: Cache flake.lock
      id: cache-flake
      uses: actions/cache@v2
      with:
        path: ./niximg.drv
        key: ${{ runner.os }}-nix-${{ steps.update.outputs.niximg-drv }}
    - name: Build LiveCD ISO image
      id: iso
      if: steps.cache-flake.outputs.cache-hit != 'true'
      run: |
        nix build ".#niximg"
        cp "result/iso/$(ls "$(readlink result)/iso/")" ./niximg.iso
        echo "::set-output name=niximg-iso::$(sha512sum ./niximg.iso|cut -d " " -f 1)"
    - name: Create Release
      id: create_release
      if: steps.cache-flake.outputs.cache-hit != 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{steps.date.outputs.date}}
        release_name: ${{ steps.date.outputs.date }}
        body: |
          This is an automated LiveCD build built on ${{ steps.date.outputs.date }}.
          The SHA-512 checksum of the image is ${{ steps.iso.outputs.niximg-iso }}.
          See [homepage](https://github.com/LEXUGE/nixos) for more information.
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      if: steps.cache-flake.outputs.cache-hit != 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./niximg.iso
        asset_name: niximg-${{ steps.date.outputs.date }}.iso
        asset_content_type: application/x-iso9660-image
    - name: Clean-up releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push release to the Telegram channel
      if: steps.cache-flake.outputs.cache-hit != 'true'
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          The `${{ github.workflow }}` workflow at `${{ steps.date.outputs.date }}` has created a new [release](${{ steps.create_release.outputs.html_url }}).
          - triggered by `${{ github.event_name }}`
          The SHA-512 checksum of the image is `${{ steps.iso.outputs.niximg-iso }}`.
          See [homepage](https://github.com/LEXUGE/nixos) for more information.
          #niximg #released
    - name: Push cached message to the Telegram channel
      if: steps.cache-flake.outputs.cache-hit == 'true'
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          The `${{ github.workflow }}` workflow at `${{ steps.date.outputs.date }}` hits a cache. No further build proceeds.
          - triggered by `${{ github.event_name }}`
          - `flake.lock` SHA-512: `${{ steps.update.outputs.flake }}`
          - derivation SHA-512: `${{ steps.update.outputs.niximg-drv }}`
          #niximg #cached
